lib/library_management_web/router.ex
defmodule LibraryManagementWeb.Router do
  use LibraryManagementWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {LibraryManagementWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LibraryManagementWeb do
    pipe_through :browser

    get "/", BookController, :index
    resources "/books", BookController do
      post "/review", BookController, :add_a_review
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", LibraryManagementWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: LibraryManagementWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/library_management/books.ex
defmodule LibraryManagement.Books do
  @moduledoc """
  The Books context.
  """

  import Ecto.Query, warn: false
  alias LibraryManagement.Repo

  alias LibraryManagement.Books.Book
  alias LibraryManagement.Reviews



  @doc """
  Returns the list of books.

  ## Examples

      iex> list_books()
      [%Book{}, ...]

  """
  def list_books do
    Repo.all(Book)
  end

  @doc """
  Gets a single book.

  Raises `Ecto.NoResultsError` if the Book does not exist.

  ## Examples

      iex> get_book!(123)
      %Book{}

      iex> get_book!(456)
      ** (Ecto.NoResultsError)

  """
  def get_book!(id), do: Repo.get!(Book, id)

  @doc """
  Creates a book.

  ## Examples

      iex> create_book(%{field: value})
      {:ok, %Book{}}

      iex> create_book(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_book(attrs \\ %{}) do
    %Book{}
    |> Book.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a book.

  ## Examples

      iex> update_book(book, %{field: new_value})
      {:ok, %Book{}}

      iex> update_book(book, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_book(%Book{} = book, attrs) do
    book
    |> Book.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a book.

  ## Examples

      iex> delete_book(book)
      {:ok, %Book{}}

      iex> delete_book(book)
      {:error, %Ecto.Changeset{}}

  """
  def delete_book(%Book{} = book) do
    Repo.delete(book)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking book changes.

  ## Examples

      iex> change_book(book)
      %Ecto.Changeset{data: %Book{}}

  """
  def change_book(%Book{} = book, attrs \\ %{}) do
    Book.changeset(book, attrs)
  end



  def add_review(book_id, review_params) do
    review_params
    |> Map.put("book_id", book_id)
    |> Reviews.create_review()
 end
end

lib/library_management/books/book.ex
defmodule LibraryManagement.Books.Book do
  use Ecto.Schema
  import Ecto.Changeset

  schema "books" do
    field :isbn, :integer
    field :publication_date, :date
    field :title, :string
    has_many(:reviews, LibraryManagement.Reviews.Review)

    timestamps()
  end

  @doc false
  def changeset(book, attrs) do
    book
    |> cast(attrs, [:title, :isbn, :publication_date])
    |> validate_required([:title, :isbn, :publication_date])
  end
end

lib/library_management_web/controllers/book_controller.ex
defmodule LibraryManagementWeb.BookController do
  use LibraryManagementWeb, :controller

  alias LibraryManagement.Books
  alias LibraryManagement.Books.Book
  alias LibraryManagement.Reviews.Review
  alias LibraryManagement.Reviews
  alias LibraryManagement.Repo

  def index(conn, _params) do
    books = Books.list_books()
    render(conn, "index.html", books: books)
  end

  def new(conn, _params) do
    changeset = Books.change_book(%Book{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"book" => book_params}) do
    case Books.create_book(book_params) do
      {:ok, book} ->
        conn
        |> put_flash(:info, "Book created successfully.")
        |> redirect(to: Routes.book_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    book =
      id
      |> Books.get_book!
      |> Repo.preload([:reviews])
    changeset = Review.changeset(%Review{}, %{})
    render(conn, "show.html", book: book, changeset: changeset)
  end

  def edit(conn, %{"id" => id}) do
    book = Books.get_book!(id)
    changeset = Books.change_book(book)
    render(conn, "edit.html", book: book, changeset: changeset)
  end

  def update(conn, %{"id" => id, "book" => book_params}) do
    book = Books.get_book!(id)

    case Books.update_book(book, book_params) do
      {:ok, book} ->
        conn
        |> put_flash(:info, "Book updated successfully.")
        |> redirect(to: Routes.book_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", book: book, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    book = Books.get_book!(id)
    {:ok, _book} = Books.delete_book(book)

    conn
    |> put_flash(:info, "Book deleted successfully.")
    |> redirect(to: Routes.book_path(conn, :index))
  end

  def add_a_review(conn, %{"review" => review_params, "book_id" => book_id}) do
    book =
      book_id
      |> Books.get_book!()
      |> Repo.preload([:reviews])
    case Books.add_review(book_id, review_params) do
      {:ok, _review} ->
        conn
        |> put_flash(:info, "review added :)")
        |> redirect(to: Routes.book_path(conn, :show, book))
      {:error, _error} ->
        conn
        |> put_flash(:error, "review not added :(")
        |> redirect(to: Routes.book_path(conn, :show, book))
    end
  end
end

lib/library_management_web/views/book_view.ex
defmodule LibraryManagementWeb.BookView do
  use LibraryManagementWeb, :view
end

lib/library_management_web/templates/book/edit.html.heex
<h1>Edit Book</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.book_path(@conn, :update, @book)) %>

<span><%= link "Back", to: Routes.book_path(@conn, :index) %></span>

lib/library_management_web/templates/book/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :isbn %>
  <%= number_input f, :isbn %>
  <%= error_tag f, :isbn %>

  <%= label f, :publication_date %>
  <%= date_select f, :publication_date %>
  <%= error_tag f, :publication_date %>

  <div>
    <%= submit "Save" %>
  </div>
</.form>

lib/library_management_web/templates/book/index.html.heex
<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Isbn</th>
      <th>Publication date</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for book <- @books do %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.isbn %></td>
      <td><%= book.publication_date %></td>

      <td>
        <span><%= link "Show", to: Routes.book_path(@conn, :show, book) %></span>
        <span><%= link "Edit", to: Routes.book_path(@conn, :edit, book) %></span>
        <span><%= link "Delete", to: Routes.book_path(@conn, :delete, book), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Book", to: Routes.book_path(@conn, :new) %></span>

lib/library_management_web/templates/book/new.html.heex
<h1>New Book</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.book_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.book_path(@conn, :index) %></span>

lib/library_management_web/templates/book/review_form.html.heex
<%= form_for @changeset, @action, fn f -> %>
  <div class="form-group">
   <label>Name</label>
   <%= text_input f, :name  %>
  </div>
  <div class="form-group">
    <label>Content</label>
    <%= textarea f, :content %>
  </div>

  <div class="form-group">
    <%= submit "Add Review" %>
  </div>
<% end %>

lib/library_management_web/templates/book/show.html.heex
<h1>Show Book</h1>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @book.title %>
  </li>

  <li>
    <strong>Isbn:</strong>
    <%= @book.isbn %>
  </li>

  <li>
    <strong>Publication date:</strong>
    <%= @book.publication_date %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.book_path(@conn, :edit, @book) %></span> |
<span><%= link "Back", to: Routes.book_path(@conn, :index) %></span>


<%= render "review_form.html", book: @book, changeset: @changeset, action: Routes.book_book_path(@conn, :add_a_review, @book) %>


<%= for review <- @book.reviews do %>
  <div class="review">
    <p>Name of reviewer:<%= review.name %> </p>
    <p>Content: <%= review.content %></p>
  </div>

<% end %>